version: "3.3"

services:
  backend-rs:
    build:
      context: backend-rs
    restart: always
    logging:
      options:
        max-size: "${DOCKER_LOGS_MAX_SIZE:-100M}"
  front:
    build:
      context: front
    restart: always
    logging:
      options:
        max-size: "${DOCKER_LOGS_MAX_SIZE:-100M}"
    ports:
      - "5000:5000"
