# vim: shiftwidth=2
version: "3.3"

services:
  backend-rs:
    build:
      context: ./backend-rs
    image: "your_registry:5005/brute-sudoku-rs/backend-rs:latest"
    restart: always
    logging:
      options:
        max-size: "${DOCKER_LOGS_MAX_SIZE:-100M}"
  front:
    build:
      context: ./front
    image: "your_registry:5005/brute-sudoku-rs/front:latest"
    restart: always
    ports:
      - "127.0.0.1:5001:5000"
    depends_on:
      - backend-rs
    logging:
      options:
        max-size: "${DOCKER_LOGS_MAX_SIZE:-100M}"
