version: "3.3"

services:
  backend-rs:
    build:
      context: ./backend-rs
    restart: always
    logging:
      options:
        max-size: "${DOCKER_LOGS_MAX_SIZE:-100M}"
  front:
    build:
      context: ./front
    restart: always
    ports:
      - 127.0.0.1:5000:5000
    depends_on:
      - backend-rs
    logging:
      options:
        max-size: "${DOCKER_LOGS_MAX_SIZE:-100M}"
