apiVersion: v1
kind: Service
metadata:
  name: backend-rs
  namespace: brute-sudoku-rs
spec:
  type: ClusterIP
  selector:
    app: backend-rs
  ports:
    - name: backend-rs-port
      targetPort: backend-rs-port
      port: 5000
      protocol: TCP
